CREATE TABLE IF NOT EXISTS customer (
	id int GENERATED BY DEFAULT AS IDENTITY,
	firstName varchar(50) not null,
	secondName varchar(50) not null,
	address1 varchar(100) not null,
	address2 varchar(100) null,
	address3 varchar(100) null,
	creditLimit NUMERIC(9,2),
	PRIMARY KEY (id)
	
);

INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('Johnny', 'Mack', '99 The Street', 'Ballytown', 'Limerick', 20000.0);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('Jill', 'O''Mahony', '33 The Lane', 'Kilthere', 'Meath', 53217.44);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('Bobby', 'O''Mahony', '33 The Lane', 'Kilthere', 'Cork', 53217.44);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('Fred', 'Lowrey', '33 The Lane', 'Kilthere', 'Meath', 53217.44);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('Mary', 'Savage', '33 The Lane', 'Kilthere', 'Cork', 53217.44);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('aaa', 'customer', 'a street', 'a town', 'a county', 77777.77);
INSERT INTO customer (firstName, secondName, address1, address2, address3, creditLimit) VALUES ('The', 'Owner', 'here', 'here', 'Cork', 99999.99);

CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(30) NOT NULL,
	password VARCHAR(50) NOT NULL,
	enabled BIT,
	id int,
	PRIMARY KEY (username),
	FOREIGN KEY (id) REFERENCES customer(id)
);

INSERT INTO users VALUES ('mackj', 'password', 1, 0);
INSERT INTO users VALUES ('omahoj', 'password', 1, 1);
INSERT INTO users VALUES ('omahob', 'password', 1, 2);
INSERT INTO users VALUES ('lowrf', 'password', 1, 3);
INSERT INTO users VALUES ('savagm', 'password', 1, 4);
INSERT INTO users VALUES ('customer', 'password', 1, 5);
INSERT INTO users VALUES ('owner', 'password', 1, 6);

CREATE TABLE IF NOT EXISTS authorities (
	username VARCHAR(30) NOT NULL,
	authority VARCHAR(50) NOT NULL,
	--PRIMARY KEY (authority),
	FOREIGN KEY (username) REFERENCES users(username)
);

INSERT INTO authorities VALUES ('mackj', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('omahoj', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('omahob', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('lowrf', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('savagm', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('customer', 'ROLE_CUSTOMER');
INSERT INTO authorities VALUES ('owner', 'ROLE_ADMIN');


CREATE TABLE IF NOT EXISTS product (
	sku int GENERATED BY DEFAULT AS IDENTITY,
	name varchar(50) not null,
	description varchar(50) not null,
	pricePerUnit NUMERIC(9,2) not null,
	unitDescription varchar(100) not null,
	stockLevel int not null,
	PRIMARY KEY (sku)
);

INSERT INTO product (name, description, pricePerUnit, unitDescription, stockLevel) VALUES ('Royal Gala', 'Apple', 2.79, 'Pack of 6', 107);
INSERT INTO product (name, description, pricePerUnit, unitDescription, stockLevel) VALUES ('Granny Smith', 'Apple', 0.35, 'Loose', 40);
INSERT INTO product (name, description, pricePerUnit, unitDescription, stockLevel) VALUES ('Fyffe', 'Banana', 3.99, 'Pack of 6', 23);
INSERT INTO product (name, description, pricePerUnit, unitDescription, stockLevel) VALUES ('Royal Blue', 'Blueberry', 2.10, '100g pack', 60);
INSERT INTO product (name, description, pricePerUnit, unitDescription, stockLevel) VALUES ('Cherry Red', 'Tomato', 2.49, 'Pack of 6', 90);


CREATE TABLE IF NOT EXISTS myOrder (
	orderID int GENERATED BY DEFAULT AS IDENTITY,
	customerID int not null,
	sku int not null,
	quantity int not null,
	total NUMERIC(9,2) not null,
	PRIMARY KEY (orderID),
	FOREIGN KEY (customerID) REFERENCES customer(id),
	FOREIGN KEY (sku) REFERENCES product(sku)
);

INSERT INTO myOrder (customerID, sku, quantity, total) VALUES (0, 0, 1, 2.79);


CREATE TABLE IF NOT EXISTS delivery (
	deliveryID int GENERATED BY DEFAULT AS IDENTITY,
	orderID int not null,
	firstName varchar(50) not null,
	secondName varchar(50) not null,
	address1 varchar(100) not null,
	address2 varchar(100) null,
	address3 varchar(100) null,
	deliveryDate date not null,
	PRIMARY KEY (deliveryID),
	FOREIGN KEY (orderID) REFERENCES myOrder(orderID)	
);

INSERT INTO delivery (orderID, firstName, secondName, address1, address2, address3, deliveryDate) VALUES (0, 'Johnny', 'Mack', '99 The Street', 'Ballytown', 'Limerick', '2013-12-23');
